// import './globals.css'
import "../assets/scss/custom.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ballo Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        data-pc-preset="preset-1"
        data-pc-sidebar-theme="light"
        data-pc-sidebar-caption="true"
        data-pc-direction="ltr"
        data-pc-theme="light"
      >
        {children}
      </body>
    </html>
  );
}
